version: '3.8'
services:
  postgresql:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: go_task
      POSTGRES_PASSWORD: go_task
      POSTGRES_DB: go_task
    volumes:
      - postgresql:/var/lib/postgresql/data
  nats:
    image: nats:2.9.7
    command: --jetstream
    ports:
      - "4222:4222"
volumes:
  postgresql: {}
