// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "go-task/core/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function with given fields: email, password
func (_m *Service) AuthenticateUser(email string, password string) (*models.User, error) {
	ret := _m.Called(email, password)

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type Service_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *Service_Expecter) AuthenticateUser(email interface{}, password interface{}) *Service_AuthenticateUser_Call {
	return &Service_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", email, password)}
}

func (_c *Service_AuthenticateUser_Call) Run(run func(email string, password string)) *Service_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Service_AuthenticateUser_Call) Return(_a0 *models.User, _a1 error) *Service_AuthenticateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_AuthenticateUser_Call) RunAndReturn(run func(string, string) (*models.User, error)) *Service_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithHashedPassword provides a mock function with given fields: email, password, fullName
func (_m *Service) CreateUserWithHashedPassword(email string, password string, fullName string) (*models.User, error) {
	ret := _m.Called(email, password, fullName)

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*models.User, error)); ok {
		return rf(email, password, fullName)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *models.User); ok {
		r0 = rf(email, password, fullName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(email, password, fullName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateUserWithHashedPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithHashedPassword'
type Service_CreateUserWithHashedPassword_Call struct {
	*mock.Call
}

// CreateUserWithHashedPassword is a helper method to define mock.On call
//   - email string
//   - password string
//   - fullName string
func (_e *Service_Expecter) CreateUserWithHashedPassword(email interface{}, password interface{}, fullName interface{}) *Service_CreateUserWithHashedPassword_Call {
	return &Service_CreateUserWithHashedPassword_Call{Call: _e.mock.On("CreateUserWithHashedPassword", email, password, fullName)}
}

func (_c *Service_CreateUserWithHashedPassword_Call) Run(run func(email string, password string, fullName string)) *Service_CreateUserWithHashedPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_CreateUserWithHashedPassword_Call) Return(_a0 *models.User, _a1 error) *Service_CreateUserWithHashedPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateUserWithHashedPassword_Call) RunAndReturn(run func(string, string, string) (*models.User, error)) *Service_CreateUserWithHashedPassword_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
