// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "go-task/core/pkg/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateWorkspaceWithUser provides a mock function with given fields: name, userId
func (_m *Service) CreateWorkspaceWithUser(name string, userId uuid.UUID) (*models.Workspace, error) {
	ret := _m.Called(name, userId)

	var r0 *models.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) (*models.Workspace, error)); ok {
		return rf(name, userId)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) *models.Workspace); ok {
		r0 = rf(name, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = rf(name, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateWorkspaceWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkspaceWithUser'
type Service_CreateWorkspaceWithUser_Call struct {
	*mock.Call
}

// CreateWorkspaceWithUser is a helper method to define mock.On call
//   - name string
//   - userId uuid.UUID
func (_e *Service_Expecter) CreateWorkspaceWithUser(name interface{}, userId interface{}) *Service_CreateWorkspaceWithUser_Call {
	return &Service_CreateWorkspaceWithUser_Call{Call: _e.mock.On("CreateWorkspaceWithUser", name, userId)}
}

func (_c *Service_CreateWorkspaceWithUser_Call) Run(run func(name string, userId uuid.UUID)) *Service_CreateWorkspaceWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_CreateWorkspaceWithUser_Call) Return(_a0 *models.Workspace, _a1 error) *Service_CreateWorkspaceWithUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateWorkspaceWithUser_Call) RunAndReturn(run func(string, uuid.UUID) (*models.Workspace, error)) *Service_CreateWorkspaceWithUser_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
